default: 
  SECRET_KEY: ''
  DEBUG: True
  ALLOWED_HOSTS: ["127.0.0.1",
                  "localhost",
                  "physics.bsu.by",
                  "www.physics.bsu.by"]
  DATABASE_URL: ""
  SECURE_SSL_REDIRECT: True
  CSRF_COOKIE_SECURE: True

