# Generated by Django 3.0.8 on 2020-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_School', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='quantumcourse',
            options={'verbose_name_plural': 'Курсы КВАНТ'},
        ),
        migrations.AlterField(
            model_name='quantumcourse',
            name='course',
            field=models.TextField(blank=True, choices=[('1', 'Квант-олимпиец'), ('2', 'Квант XI'), ('3', 'Квант X'), ('4', 'Квант IX'), ('5', 'Квант-юни')], help_text='Не изменять!', max_length=10, null=True),
        ),
    ]
