# Generated by Django 3.0.4 on 2020-03-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Uploads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff_unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("position", models.TextField(blank=True, null=True)),
                (
                    "position_var",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("10", "Заведующий кафедры"),
                            ("11", "Секретарь"),
                            ("12", "Профессор"),
                            ("13", "Заведующий сектором"),
                            ("14", "Старший преподаватель"),
                            ("15", "Доцент"),
                            ("16", "Ассистент"),
                            ("17", "Заведующий лабораторией"),
                            ("18", "Заведующий СНИЛ"),
                            ("20", "Главный научн. сотруд."),
                            ("21", "Ведущий научн. сотруд."),
                            ("22", "Старший научн. сотруд."),
                            ("22", "Научный сотруд."),
                            ("23", "Младший научн. сотруд."),
                            ("24", "Стажер м. н. с."),
                            ("30", "Ведущий инженер"),
                            ("31", "Инженер 1 категории"),
                            ("32", "Инженер 2 категории"),
                            ("33", "Инженер"),
                            ("34", "Ведущий специалист"),
                            ("35", "Лаборант"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "k_math",
                                "Кафедра высшей математики и математической физики",
                            ),
                            ("k_common_phys", "Кафедра общей физики"),
                            (
                                "k_astro_phys",
                                "Кафедра теоретической физики и астрофизики",
                            ),
                            ("k_t_t", "Кафедра физики твердого тела"),
                            (
                                "k_nano",
                                "Кафедра физики полупроводников и наноэлектроники",
                            ),
                            ("k_energy", "Кафедра энергофизики"),
                            ("k_nuclear", "Кафедра ядерной физики"),
                            ("k_lazer", "Кафедра лазерной физики и спектроскопии"),
                            (
                                "k_optics",
                                "Кафедра физической оптики и прикладной информатики",
                            ),
                            ("k_k_m", "Кафедра компьютерного моделирования"),
                            ("k_bio", "Кафедра биофизики"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("slug", models.URLField(max_length=250)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/staff"),
                ),
                ("description", models.TextField()),
                (
                    "uploads",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Uploads.Uploads",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Сотрудники",},
        ),
    ]
