# Generated by Django 3.0.8 on 2021-02-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210205_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_unit',
            name='academic_rank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_unit',
            name='academic_rank_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_unit',
            name='academic_rank_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
