# Generated by Django 3.0.8 on 2020-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagestatisticnumber",
            options={"verbose_name_plural": "Физический факультет в цифрах"},
        ),
        migrations.AddField(
            model_name="mainpagestatisticnumber",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mainpagestatisticnumber",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
