# Generated by Django 3.0.8 on 2021-02-05 19:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_noteinmedia'),
    ]

