# Generated by Django 3.0.8 on 2021-02-05 20:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20210205_2229"),
    ]
