# Generated by Django 3.0.8 on 2021-02-14 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210205_2348'),
    ]

    
    ]
