# Generated by Django 3.0.8 on 2021-03-24 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210214_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteinmedia',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='title_ru',
            field=models.TextField(null=True),
        ),
    ]
