# Generated by Django 3.0.8 on 2021-03-24 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20210214_1409"),
    ]
