# Generated by Django 3.0.8 on 2021-03-24 15:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210324_1514'),
    ]


