# Generated by Django 3.2.12 on 2022-04-01 16:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210324_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteinmedia',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noteinmedia',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(blank=True, choices=[('draft', 'draft'), ('published', 'published')], help_text='Обязательное поле!', max_length=10, null=True),
        ),
    ]
