name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ENV_FOR_DYNACONF: GITHUB_WORKFLOW

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: bsuphys
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run migrations
      run: python core/manage.py migrate

    - name: Test with pytest
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
      working-directory: ./core
      run: pytest
    
